### ISSUE TITLE
Remove .DS_Store and add to .gitignore

### ISSUE THREAD

**Issue by mdhishaamakhtar** [GDGVIT/keats-backend#3]
**Describe the bug**
The Repository contains .DS_Store files which are not relevant and belong in the .gitignore

**Possible solution**
Delete all .DS_Store files, add them to .gitignore, then commit and push

**Comment by mdhishaamakhtar** [comment]
@Krishap-s have a look

**Comment by Krishap-s** [comment]
Sure, I will fix it.
